orange/thresh_0: 137
orange/erosion_0: 1
orange/thresh_1: 106
orange/close_1: 0
orange/open_1: 6
orange/initial_range_value: 241
orange/range_width: 36
orange/open_2: 0
orange/close_2: 20
orange/open_3: 5

red/thresh_0: 52
red/erosion_0: 2
red/thresh_1: 0
red/close_1: 0
red/open_1: 0
red/initial_range_value: 245
red/range_width: 14
red/open_2: 3
red/close_2: 4
red/open_3: 2

green/thresh_0: 36
green/erosion_0: 1
green/thresh_1: 55
green/close_1: 5
green/open_1: 5
green/initial_range_value: 112
green/range_width: 40
green/open_2: 5
green/close_2: 0
green/open_3: 2

blue/thresh_0: 36
blue/erosion_0: 1
blue/thresh_1: 85
blue/close_1: 0
blue/open_1: 0
blue/initial_range_value: 150
blue/range_width: 28
blue/open_2: 1
blue/close_2: 11
blue/open_3: 2

yellow/thresh_0: 76
yellow/erosion_0: 1
yellow/thresh_1: 61
yellow/close_1: 0
yellow/open_1: 6
yellow/initial_range_value: 22
yellow/range_width: 28
yellow/open_2: 3
yellow/close_2: 8
yellow/open_3: 0
