orange/initial_range_value: 1241
orange/range_width: 11136

red/initial_range_value: 214
red/range_width: 54

green/initial_range_value: 103
green/range_width: 39

blue/initial_range_value: 152
blue/range_width: 15

yellow/initial_range_value: 22
yellow/range_width: 28
