orange/initial_range_value: 1241
orange/range_width: 11136

red/initial_range_value: 245
red/range_width: 25

green/initial_range_value: 118
green/range_width: 24

blue/initial_range_value: 152
blue/range_width: 15

yellow/initial_range_value: 23
yellow/range_width: 25
