module: A

area1_x: 0.679
area1_y: -2.148
area1_orientation: -2.600

area2_x: 0.422
area2_y: -1.432
area2_orientation: -2.097

area3_x: 0.206
area3_y: -1.142
area3_orientation: -2.574

area4_x: 0.674
area4_y: -2.302
area4_orientation: 0.464

area5_x: 0.288
area5_y: -1.577
area5_orientation: 0.121

area6_x: 0.208
area6_y: -1.437
area6_orientation: 0.651

casa_x: 2.120
casa_y: -1.478
casa_orientation: -2.605

deposito1_x: 2.694
deposito1_y: -0.213
deposito1_orientation: 2.105

deposito2_x: 2.022
deposito2_y: -0.576
deposito2_orientation: 2.171

deposito3_x: 1.620
deposito3_y: -1.029
deposito3_orientation: 2.119

store_deposito1_x: 2.464
store_deposito1_y: -0.510
store_deposito1_orientation: 0.534

store_deposito2_x: 2.012
store_deposito2_y: -0.816
store_deposito2_orientation: 0.526

store_deposito3_x: 1.385
store_deposito3_y: -1.136
store_deposito3_orientation: 0.543

pedido_x: 2.431
pedido_y: -1.152
pedido_orientation: 0.542
