module: A

area1_x: 0.696
area1_y: -2.076
area1_orientation: -2.491

area2_x: 0.503
area2_y: -2.005
area2_orientation: 2.898

area3_x: 0.076
area3_y: -1.138
area3_orientation: -2.406

area4_x: 0.658
area4_y: -2.278
area4_orientation: 0.514

area5_x: 0.458
area5_y: -2.057
area5_orientation: 1.191

area6_x: 0.092
area6_y: -1.202
area6_orientation: 0.483

casa_x: 2.120
casa_y: -1.478
casa_orientation: -2.605

deposito1_x: 2.694
deposito1_y: -0.213
deposito1_orientation: 2.105

deposito2_x: 2.142
deposito2_y: -0.563
deposito2_orientation: 2.121

deposito3_x: 1.526
deposito3_y: -0.828
deposito3_orientation: 2.098

store_deposito1_x: 2.707
store_deposito1_y: -0.407
store_deposito1_orientation: 0.553

store_deposito2_x: 2.150
store_deposito2_y: -0.732
store_deposito2_orientation: 0.534

store_deposito3_x: 1.506
store_deposito3_y: -1.013
store_deposito3_orientation: 0.523

pedido_x: 2.612
pedido_y: -1.134
pedido_orientation: 0.532
